export const KEYWORDS = [
  "Anxiolytic",
  "Treatment-resistant depression",
  "Major depressive disorder",
  "Precision Psychiatry",
  "Panic Disorder",
  "BI 1358894",
  "BNC-210",
  "PRAX-114",
  "JZP-150",
  "LU AG06466",
  "NYV-783",
  "SRX246",
  "TNX-102",
  "Darigabat",
  "JNJ-61393215",
  "7-Oxoprasterone",
  "Brexpiprazole",
  "Iloperidone",
  "Riluzole",
  "CVL-354",
  "Boehringer Ingelheim",
  "Bionomics",
  "Azevan Pharmaceuticals",
  "Otsuka",
  "Cerevel",
  "Vasopressin V1A antagonist",
  "Seasonal affective disorder",
  "Computational Neuroscience",
  "SK Life Sciences",
  "Atai Life Sciences",
  "Domona Pharmaceuticals",
  "Neurocrine Biosciences",
  "Minerva Neurosciences",
  "Harmony Biosciences",
  "HRMY",
  "Schizoprenia",
  "Manifest Technologies",
  "Sama Therapeutics",
  "Montara Therapeutics",
  "Rezo TX",
  "KdT Ventures",
  "Montara Therapeutics",
  "CNS",
  "neuroscience",
  "brain",
  "anxiolytic",
  "antidepressant",
  "depression",
  "anxiety",
  "neuropsychiatry",
  "psychiatry",
  "bio.xyz",
  "peptide",
  "nootropic",
  "biohacking",
  "SSRI",
  "SARMs",
  "LSD",
  "MDMA",
  "SNRI",
  "PET scan",
  "fMRI",
  "PET",
  "Psychiatry",
  "Neuroscience",
  "Neurotherapeutics",
  "Neuropharmacology",
  "Neurobiology",
  "Neuroimaging",
  "Neurotherapy",
  "Neurotherapies",
  "Neurotherapeutic",
  "Neurotherapeutics",
  "DeSci",
  "Psychedelic therapy",
  "Psilocybin",
  "Ketamine",
  "Panic Disorder",
  "PTSD",
  "Bipolar Disorder",
  "Schizophrenia Spectrum Disorder",
  "Schizophrenia Disorder",
];
